name: animatediff_pt2
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - accelerate==0.25.0
    - diffusers==0.26.1
    - transformers==4.25.1
    - imageio==2.27.0
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio==3.41.2
    - wandb
    - imageio-ffmpeg
    - av